In [2]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

In [3]:
data = np.random.randint(0,100,(10,2)) # random between 0~100, 10 rows, 2 columns

In [4]:
data

array([[14, 22],
       [37, 64],
       [89, 82],
       [61, 56],
       [78, 14],
       [42, 44],
       [96, 94],
       [56,  4],
       [58, 63],
       [72, 66]])

In [5]:
scaler_model = MinMaxScaler()

In [6]:
type(scaler_model)

sklearn.preprocessing.data.MinMaxScaler

In [7]:
scaler_model.fit(data)

d:\programs\python\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


MinMaxScaler(copy=True, feature_range=(0, 1))

In [8]:
scaler_model.transform(data) // scaler data to 0~1

array([[0.        , 0.2       ],
       [0.2804878 , 0.66666667],
       [0.91463415, 0.86666667],
       [0.57317073, 0.57777778],
       [0.7804878 , 0.11111111],
       [0.34146341, 0.44444444],
       [1.        , 1.        ],
       [0.51219512, 0.        ],
       [0.53658537, 0.65555556],
       [0.70731707, 0.68888889]])

In [9]:
import pandas as pd

In [10]:
mydata = np.random.randint(0,101,(50,4))

In [11]:
mydata

array([[ 0, 98, 13, 58],
       [62, 61,  5, 31],
       [45, 95, 21, 57],
       [42, 74, 92, 14],
       [12, 69, 90, 45],
       [63, 88,  9, 30],
       [86, 39, 79, 56],
       [98, 10, 27,  5],
       [87, 60, 20, 86],
       [ 8, 92, 79, 71],
       [71, 81, 81, 67],
       [ 6, 73, 27, 21],
       [59, 56, 53, 84],
       [88, 28, 75, 26],
       [21, 92, 36, 34],
       [38, 42, 54, 53],
       [19, 22, 70, 45],
       [ 4, 10, 11, 62],
       [16, 26, 51, 18],
       [ 1, 37, 97, 68],
       [33, 18, 30, 39],
       [45, 56, 42, 87],
       [27, 55, 71, 18],
       [40, 60, 88, 17],
       [32, 35, 47, 88],
       [ 4, 24, 78, 44],
       [ 1, 47, 52, 78],
       [54, 88, 81, 47],
       [99, 16, 95,  3],
       [22, 86, 83, 46],
       [33, 55, 48, 71],
       [89, 15, 38, 55],
       [76, 91,  0, 21],
       [ 2, 86, 79, 36],
       [51, 59, 45, 99],
       [74,  3, 52, 72],
       [ 2, 52, 76, 91],
       [18, 96, 65,  5],
       [83,  1, 21, 39],
       [55, 67, 17, 43],


In [19]:
df = pd.DataFrame(data=mydata,columns = ['f1','f2','f3','label']) # create a data frame 

In [20]:
df

f1  f2  f3  label
0    0  98  13     58
1   62  61   5     31
2   45  95  21     57
3   42  74  92     14
4   12  69  90     45
5   63  88   9     30
6   86  39  79     56
7   98  10  27      5
8   87  60  20     86
9    8  92  79     71
10  71  81  81     67
11   6  73  27     21
12  59  56  53     84
13  88  28  75     26
14  21  92  36     34
15  38  42  54     53
16  19  22  70     45
17   4  10  11     62
18  16  26  51     18
19   1  37  97     68
20  33  18  30     39
21  45  56  42     87
22  27  55  71     18
23  40  60  88     17
24  32  35  47     88
25   4  24  78     44
26   1  47  52     78
27  54  88  81     47
28  99  16  95      3
29  22  86  83     46
30  33  55  48     71
31  89  15  38     55
32  76  91   0     21
33   2  86  79     36
34  51  59  45     99
35  74   3  52     72
36   2  52  76     91
37  18  96  65      5
38  83   1  21     39
39  55  67  17     43
40  46  85  25     51
41  62  98  50     20
42  86  15  61     28
43  61  30  33     77
44   9  80  15     85
45  86  88   9     70
46  29  72  46     16
47  49  17  99     20
48  37  97  60     14
49  18  95   5     48

In [21]:
x = df[['f1','f2','f3']]

In [22]:
y = df['label']

In [23]:
from sklearn.model_selection import train_test_split

In [25]:
x_train,x_test, y_train, y_test = train_test_split(x,y,test_size=0.3,random_state=101)

In [26]:
x_train.shape

(35, 3)

In [27]:
x_test.shape

(15, 3)

In [28]:
y_train.shape

(35,)

In [30]:
y_test.shape

(15,)